"""empty message

Revision ID: 3f9b152cec25
Revises: 2c25eb72ca1b
Create Date: 2019-03-19 17:39:21.908127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9b152cec25'
down_revision = '2c25eb72ca1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('projectname', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projectlist')
    # ### end Alembic commands ###
