"""'test'

Revision ID: 760d615570c2
Revises: 0e53f70dc789
Create Date: 2019-07-13 08:47:50.173504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760d615570c2'
down_revision = '0e53f70dc789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_authors', sa.Column('booksname', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'tbl_authors', ['booksname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_authors', type_='unique')
    op.drop_column('tbl_authors', 'booksname')
    # ### end Alembic commands ###
